[project]
name = "python-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.3.0",
    "pytesseract>=0.3.13",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.15.0",
]
