[project]
name = "python-ocr"
version = "v2.0.1"
description = "Python OCR process for fanyi"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jieba>=0.42.1",
    "paddleocr==3.3.0",
    "paddlepaddle==3.2.0",
    "pillow>=11.3.0",
    "ruff>=0.12.8",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.15.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
indent-width = 2
  
[tool.ruff.format]
quote-style="double"
line-ending="lf"
indent-style="space"
